### ISSUE TITLE
Disabled `Try it out`

### ISSUE THREAD

**Issue by windchime-yk** [rwl-dev/specfront#7]
GET and HEAD only enabled `Try it out`.

**Comment by thawankeane** [comment]
@windchime-yk there is a reason for this pr? Why enable try it out for those methods only?

**Comment by windchime-yk** [comment]
@thawankeane 
Specfront was intended to be touched by non-developers when it was created.
In this case, the `Try it out` buttons (POST, DELETE, etc.) were disabled because there was a concern that users would mistakenly change or delete data if the Try it out buttons were present.
